# Generated by Django 4.1.5 on 2023-01-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal_sync_magic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncconfigs",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
