# Generated by Django 4.1.5 on 2023-01-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal_sync_magic", "0002_alter_syncconfigs_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercalendar",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalendar",
            name="last_error",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="usercalendar",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
