# Generated by Django 4.1.5 on 2023-01-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cal_sync_magic",
            "0003_usercalendar_deleted_usercalendar_last_error_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usercalendar",
            name="last_sync_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
