# Generated by Django 4.1.5 on 2023-01-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal_sync_magic", "0004_usercalendar_last_sync_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="googleaccount",
            name="credential_expirery",
            field=models.DateTimeField(null=True),
        ),
    ]
