# Generated by Django 4.1.5 on 2023-01-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal_sync_magic', '0006_rename_credential_expirery_googleaccount_credential_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercalendar',
            name='webhook_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
