# Generated by Django 4.1.5 on 2023-01-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal_sync_magic', '0007_usercalendar_webhook_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleaccount',
            name='calendar_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='delete_events_from_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='more_spam_filter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='scopes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='second_chance_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syncconfigs',
            name='match_creator_regex',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='syncconfigs',
            name='match_title_regex',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='syncconfigs',
            name='rewrite_regex',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
