# Generated by Django 4.1.5 on 2023-01-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal_sync_magic', '0008_googleaccount_calendar_sync_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncconfigs',
            name='default_title',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='syncconfigs',
            name='hide_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syncconfigs',
            name='min_sched',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='syncconfigs',
            name='warn_location_mismatch',
            field=models.BooleanField(default=False),
        ),
    ]
