# Generated by Django 4.1.5 on 2023-01-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal_sync_magic', '0010_alter_syncconfigs_default_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleaccount',
            name='scopes',
        ),
    ]
