# Generated by Django 4.1.5 on 2023-02-01 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal_sync_magic', '0011_remove_googleaccount_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncconfigs',
            name='min_sched',
        ),
        migrations.RemoveField(
            model_name='syncconfigs',
            name='warn_location_mismatch',
        ),
        migrations.AddField(
            model_name='syncconfigs',
            name='invitee_skip_event_threshold',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='CalendarRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sched', models.DurationField(null=True)),
                ('warn_location_mismatch', models.BooleanField(default=False)),
                ('allow_list_min_sched', models.CharField(blank=True, max_length=1000, null=True)),
                ('soft_maybe_conflict', models.BooleanField(default=False)),
                ('decline_conflict', models.BooleanField(default=False)),
                ('allow_list_conflict', models.CharField(blank=True, max_length=1000, null=True)),
                ('try_to_delete_canceled_events', models.BooleanField(default=False)),
                ('calendars', models.ManyToManyField(related_name='rule_calendars', to='cal_sync_magic.usercalendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
