# Generated by Django 4.1.5 on 2023-02-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal_sync_magic', '0012_remove_syncconfigs_min_sched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncconfigs',
            name='invitee_skip_event_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
