# Generated by Django 4.1.5 on 2023-02-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal_sync_magic", "0013_alter_syncconfigs_invitee_skip_event_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleaccount",
            name="credentials",
            field=models.CharField(max_length=5000),
        ),
    ]
