# Generated by Django 4.1.5 on 2023-02-10 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cal_sync_magic", "0015_alter_calendarrules_id_alter_syncconfigs_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercalendar",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
