# Generated by Django 4.1.5 on 2023-02-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal_sync_magic", "0016_usercalendar_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercalendar",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="calendarrules",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="syncconfigs",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
