# Generated by Django 4.1.5 on 2023-02-11 01:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "cal_sync_magic",
            "0017_remove_usercalendar_uuid_alter_calendarrules_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usercalendar",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
