# Generated by Django 4.1.5 on 2023-02-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal_sync_magic", "0018_usercalendar_uuid_alter_calendarrules_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercalendar",
            name="last_error",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
