# Generated by Django 4.1.5 on 2023-02-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal_sync_magic", "0021_alter_usercalendar_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercalendar",
            name="uuid",
        ),
    ]
